sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
# 3.7 is not currently supported, matrix config added as workaround
#  - "3.7"
matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true
install:
  - pip install tox-travis
script: tox
